WebApplication/Models/Vocabulary.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int Id { get; set; }
        public string EngWord { get; set; }
        public string VnWord { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Spelling { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Bookmark { get; set; }
    }
}

WebApplication/Controllers/VocabulariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpeakOutWeb.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace SpeakOutWeb.Controllers
{
    public class VocabulariesController : Controller
    {
        private SpeakOutEntities db = new SpeakOutEntities();

        // GET: Vocabularies
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (HttpContext.User.Identity.GetUserName() == "" || HttpContext.User.Identity.GetUserName() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.CurrentSort = sortOrder;
            ViewBag.VocabSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.BookmarkSortParm = sortOrder == "Bookmark" ? "bookmark_true" : "Bookmark";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var userId = HttpContext.User.Identity.GetUserName();
            var vocab = db.Vocabularies.Where(s => s.UserId == userId);
            if (!String.IsNullOrEmpty(searchString))
            {
                vocab = vocab.Where(s => s.EngWord.Contains(searchString)
                                       || s.VnWord.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    vocab = vocab.OrderByDescending(s => s.EngWord);
                    break;
                case "Date":
                    vocab = vocab.OrderBy(s => s.CreatedDate);
                    break;
                case "date_desc":
                    vocab = vocab.OrderByDescending(s => s.CreatedDate);
                    break;
                case "Bookmark":
                    vocab = vocab.OrderByDescending(s => s.EngWord).Where(x => x.Bookmark == false);
                    break;
                case "bookmark_true":
                    vocab = vocab.OrderByDescending(s => s.EngWord).Where(x => x.Bookmark == true);
                    break;
                default:  // Name ascending 
                    vocab = vocab.OrderBy(s => s.EngWord);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(vocab.ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        public ActionResult getVocabularies()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var userName = User.Identity.GetUserName();
            if (userName == null || userName == "")
            {
                return Json("Không tìm thấy từ điển của bạn", JsonRequestBehavior.AllowGet);
            }
            var dictionaries = db.Vocabularies.Where(s => s.UserId == userName && s.Bookmark== false).OrderByDescending(x => x.Id).ToList();
            return Json(dictionaries, JsonRequestBehavior.AllowGet);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult SaveEntity(Vocabulary vocabulary)
        {

            var currentUser = HttpContext.User.Identity.GetUserName();
            db.Configuration.ProxyCreationEnabled = false;
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                if (vocabulary.Id == 0)
                {
                    if(vocabulary.Spelling==null || (vocabulary.Spelling == "" && vocabulary.VnWord==""))
                    {
                        return Json("Không tìm thấy tư vựng của bạn", JsonRequestBehavior.AllowGet);
                    }
                    var listAvailable = db.Vocabularies.Where(x=>x.UserId== currentUser).ToList();
                    foreach (var item in listAvailable)
                    {
                        if (item.EngWord == vocabulary.EngWord.ToLower())
                        {
                            return Json("Từ vựng của bạn đã được lưu", JsonRequestBehavior.AllowGet);
                        }
                    }
                    vocabulary.VnWord = vocabulary.VnWord.Trim();
                    vocabulary.EngWord = vocabulary.EngWord.ToLower();
                    vocabulary.CreatedDate = DateTime.Now;
                    vocabulary.Bookmark = false;
                    vocabulary.UserId = currentUser;
                    if (vocabulary.UserId == null || vocabulary.UserId == "")
                    {
                        return Json("Kiểm tra đặng nhập của bạn!", JsonRequestBehavior.AllowGet);
                    }
                    db.Vocabularies.Add(vocabulary);
                }
                else
                {
                    vocabulary.Bookmark = true;
                    db.Entry(vocabulary).State = EntityState.Modified;
                }
                db.SaveChanges();
                return Json("Lưu thành công", JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateBookmark(int Id)
        {
            if (HttpContext.User.Identity.GetUserName() == "" || HttpContext.User.Identity.GetUserName() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            Vocabulary vocabulary = db.Vocabularies.Single(x => x.Id == Id);
            vocabulary.Bookmark = true;
            db.Entry(vocabulary).State = EntityState.Modified;
            db.SaveChanges();
            return Json("Lưu thành công", JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult CheckAvailable(string checkWord)
        {
            if (HttpContext.User.Identity.GetUserName() == "" || HttpContext.User.Identity.GetUserName() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var currentUser = User.Identity.GetUserName();
            var listVocab = db.Vocabularies.Where(x => x.UserId == currentUser).ToList();
            var countWord = 0;
            foreach (var item in listVocab)
            {
                if (item.EngWord == checkWord.ToLower())
                {
                    countWord++;
                }
            }
            return Json(countWord, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication/Views/Vocabularies/Index.cshtml
@model PagedList.IPagedList<SpeakOutWeb.Models.Vocabulary>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}
<link href="~/Library/css/dictionaryStyle.css" rel="stylesheet" />
@Styles.Render("~/Content/css")
<article id="webslides" class="vertical">
    <section class="bg-white">
        <span class="background bg1" style="background-image:url('@Url.Content("~/Library/images/real-estate-background-images-6.jpg")')"></span>
        <div class="container">
            @using (Html.BeginForm("Index", "Vocabularies", FormMethod.Get))
            {
                <p class="formSearch">
                    Tìm nhóm theo tên: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Tìm kiếm" id="submitSearch" />
                   
                </p>
            }

            <table class="table">
                <tr >
                    <th>
                        <button id="sortButton" title="Click here to sort following name">@Html.ActionLink("Từ vựng của bạn", "Index", new { sortOrder = ViewBag.VocabSortParm, currentFilter = ViewBag.CurrentFilter })</button>
                    </th>
                    <th style="float:left">
                        <button id="sortCreatedDateButton" title="Click here to sort following created date">@Html.ActionLink("Ngày đã tạo", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })</button>
                    </th>
                    <th>
                        <button id="sortCreatedDateButton" title="Click here to sort following created date">@Html.ActionLink("Đánh dấu đã thuộc", "Index", new { sortOrder = ViewBag.BookmarkSortParm, currentFilter = ViewBag.CurrentFilter})</button>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>

                            <span id="engWord"><strong>@Html.DisplayFor(modelItem => item.EngWord)</strong></span>
                            <span id="pronoun">@Html.DisplayFor(modelItem => item.Spelling)</span>
                            <button id="speakButton" class="btn speakButton" data-speak="@item.EngWord">
                                <img src="~/Content/500px-Speaker_Icon.svg.png" />
                            </button><br />
                            <span id="vnWord">@Html.DisplayFor(modelItem => item.VnWord)</span>
                        </td>
                        <td>
                            @item.CreatedDate;
                        </td>
                        <td style="text-align:center;vertical-align: middle;">
                            @if (item.Bookmark == false)
                            {
                                <button class="btn" type="submit" id="bookmarkedButton" data-id="@item.Id"><i class="far fa-bookmark"></i></button>
                            }

                        </td>

                    </tr>
                }
            </table>
            <br />
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) trên @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </section>
</article>
@section Script1{
    <script>
        $('#bookmarkedButton').on('click', function () {
            $.ajax({
            type: 'POST',
            url: '@Url.Action("../Vocabularies/UpdateBookmark")',
            contentType: "application/json; charset=utf-8",
            data: '{ "Id": "' + $(this).attr("data-id") + '" }',
                success: function (result, status, xhr) {
                    window.location.reload();
            },
            error: function (xhr, status, error) {
                alert('Result: ' + status + ' ' + error + ' ' + xhr.status + ' ' + xhr.statusText)
            }
        });
        });
        $('.speakButton').on('click', function () {
            var synth = window.speechSynthesis;
            var utterThis = new SpeechSynthesisUtterance($(this).attr("data-speak"));
            synth.speak(utterThis);
        });
    </script>

}