WebApplication/Controllers/UserAudioesController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using SpeakOutWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpeakOutWeb.Controllers
{
    public class UserAudioesController : Controller
    {
        private SpeakOutEntities db = new SpeakOutEntities();
        // GET: Audioes
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (HttpContext.User.Identity.GetUserName() == "" || HttpContext.User.Identity.GetUserName() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.CurrentSort1 = sortOrder;
            ViewBag.DateSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var currentUser = HttpContext.User.Identity.GetUserName();
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter1 = searchString;
            var userAudios = db.UserAudioes.Where(x => x.UserId == currentUser);
            if (!String.IsNullOrEmpty(searchString))
            {
                userAudios = userAudios.Where(s => s.TextAudio.Contains(searchString));
            }
            switch(sortOrder)
            {
                case "name_desc":
                    userAudios = userAudios.OrderBy(s => s.CreateDate);
                break;
                default:  // Name ascending 
                    userAudios = userAudios.OrderByDescending(s => s.CreateDate);
                break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(userAudios.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult LoadAudio(int id)
        {
            var audioBytes = db.UserAudioes.Where(w => w.Id == id).Single();
            return base.File(audioBytes.LinkAudio, "audio/mp3");
        }
    }
}

WebApplication/Views/UserAudioes/Index.cshtml
@model PagedList.IPagedList<SpeakOutWeb.Models.UserAudio>
@using Microsoft.AspNet.Identity
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/css")
<style>
    #buttonControl a {
        text-decoration: none !important;
        color: white !important;
    }
</style>
<style>
    span.line:hover {
        text-decoration: underline;
    }

    span.bold {
        font-weight: bold;
    }

    span.italic {
        font-style: italic;
    }

    span.underline {
        text-decoration: underline;
    }

    span.overline {
        border-top: dashed 1px;
    }

    span.word {
        cursor: pointer;
    }

    span.red {
        color: red;
    }

    span.green {
        color: green;
    }

    span.blue {
        color: blue;
    }
</style>
<article id="webslides" class="vertical">
    <section class="bg-white  ">
        <div class="container">
            <div>

                @using (Html.BeginForm("Index", "UserAudioes", FormMethod.Get, new { @class = "formSearch" }))
                {
                    <p class="formSearch">
                        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter1 as string)
                        <input type="submit" value="Search" id="submitSearch" />
                    </p>
                }
            </div>
            <table class="table">
                <tr>
                    <th>
                        STT
                    </th>
                    <th>
                        <button id="sortButton">@Html.ActionLink("   NGÀY TẠO ", "Index", new { sortOrder = ViewBag.DateSort }, new { @class = "glyphicon glyphicon-sort-by-alphabet" })</button>
                    </th>
                    <th>
                        Bài nghe
                    </th>
                    <th>
                        Đoạn văn
                    </th>
                    <th></th>
                </tr>
                @{
                    int count = 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@count</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreateDate)
                            </td>
                            <td>
                                <audio controls src="@Url.Action("LoadAudio", new { id = item.Id })" ) />
                            </td>
                            <td>
                                <script>
                    document.write(unescape("@item.TextAudio"));
                                </script>
                            </td>
                        </tr>
                        count++;
                    }
                }
            </table>
            <br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort1, currentFilter = ViewBag.CurrentFilter1 }))
        </div>
    </section>
</article>