WebApplication/Models/UserLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ContentReading { get; set; }
        public string UserId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}

WebApplication/Controllers/UserLogsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using SpeakOutWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SpeakOutWeb.Controllers
{
    public class UserLogsController : Controller
    {
        private SpeakOutEntities db = new SpeakOutEntities();

        // GET: UserLogs
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (HttpContext.User.Identity.GetUserName() == "" || HttpContext.User.Identity.GetUserName() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.CurrentSort = sortOrder;
            ViewBag.LogSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var userId = HttpContext.User.Identity.GetUserName();
            var log = db.UserLogs.Where(s => s.UserId == userId);
            if (!String.IsNullOrEmpty(searchString))
            {
                log = log.Where(s => s.ContentReading.Contains(searchString)
                                       || s.Type.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    log = log.OrderByDescending(x => x.UserId);
                    break;
                case "Date":
                    log = log.OrderBy(s => s.CreateDate);
                    break;
                case "date_desc":
                    log = log.OrderByDescending(s => s.CreateDate);
                    break;
                case "name_asc":
                    log = log.OrderByDescending(s => s.Type).Where(x => x.Type == "Bài nói");
                    break;
                default:  // Name ascending 
                    log = log.OrderByDescending(x=>x.CreateDate);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(log.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult SaveLogs(string text)
        {
            var currentUser = HttpContext.User.Identity.GetUserName();
            db.Configuration.ProxyCreationEnabled = false;
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                if (currentUser != "" || currentUser != null)
                {
                    UserLog userLog = new UserLog();
                    userLog.CreateDate = DateTime.Now;
                    userLog.ContentReading = text;
                    userLog.UserId = currentUser;
                    userLog.Type = "Đoạn văn";
                    db.UserLogs.Add(userLog);
                    db.SaveChanges();
                }
               
                return Json("Lưu thành công", JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult SaveLogDetails(string text, DateTime createDate, DateTime endDate)
        {
            var currentUser = HttpContext.User.Identity.GetUserName();
            db.Configuration.ProxyCreationEnabled = false;
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                if (currentUser != "" || currentUser != null)
                {
                    UserLog userLog = new UserLog();
                    userLog.CreateDate = createDate;
                    userLog.EndDate = endDate;
                    userLog.ContentReading = text;
                    userLog.UserId = currentUser;
                    userLog.Type = "Đoạn văn";
                    db.UserLogs.Add(userLog);
                    db.SaveChanges();
                }

                return Json("Lưu thành công", JsonRequestBehavior.AllowGet);
            }
        }



    }
}

WebApplication/Views/UserLogs/Index.cshtml
@model PagedList.IPagedList<SpeakOutWeb.Models.UserLog>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/css")
<style>
    #buttonControl a {
        text-decoration: none !important;
        color: white !important;
    }
</style>
<style>
    span.line:hover {
        text-decoration: underline;
    }

    span.bold {
        font-weight: bold;
    }

    span.italic {
        font-style: italic;
    }

    span.underline {
        text-decoration: underline;
    }

    span.overline {
        border-top: dashed 1px;
    }

    span.word {
        cursor: pointer;
    }

    span.red {
        color: red;
    }

    span.green {
        color: green;
    }

    span.blue {
        color: blue;
    }
</style>
<article id="webslides" class="vertical">
    <section class="bg-white">
        <div class="container">
            @using (Html.BeginForm("Index", "UserLogs", FormMethod.Get))
            {
                <p class="formSearch">
                    Tìm theo đoạn văn và loại: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Search" id="submitSearch" style="width:80px" />

                </p>
            }
            <table class="table">
                <tr>
                    <th>
                        STT
                    </th>
                    <th>
                        LOẠI
                    </th>
                    <th>
                        @Html.ActionLink("NGÀY TẠO", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        KẾT THÚC
                    </th>
                    <th>
                        THỜI GIAN
                    </th>
                    <th>
                        ĐOẠN VĂN
                    </th>
                </tr>
                @{int count = 1;
                    foreach (var item in Model)
                    {
                        <input type="hidden" data-id="@item.Id" />
                        <tr class="active">
                            <td>
                                @count
                            </td>
                            <td>
                                @item.Type
                            </td>
                            <td>
                                @item.CreateDate
                            </td>
                            <td>
                                @item.EndDate
                            </td>
                            <td>
                                @if (item.EndDate != null)
                                {
                                    @(item.EndDate - item.CreateDate);
                                }

                            </td>
                            <td id="speechContext1">
                                <button class="btn btn-info showMore">Hiên thị thêm</button>
                                <div class="speechContext">
                                    <script>
                                        document.write(unescape("@item.ContentReading"));
                                    </script>
                                </div>
                                <button class="btn btn-success showAgain" style="width:20px;height:20px;text-align:center;vertical-align:middle">^</button>
                            </td>
                        </tr>
                        count++;
                    }
                }
            </table>
            <br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </section>
</article>
@section Scripts{
    <script>
        $(".speechContext").hide();
        $(".showAgain").hide();
        $(".showMore").show();
        $(".showMore").on('click', function () {
            $(this).parent().find(".speechContext").show();
            $(this).parent().find(".showAgain").show();
            $(this).css("display", "none")
        })
        $(".showAgain").on('click', function () {
            $(this).parent().find(".speechContext").css("display", "none");
            $(this).parent().find(".showMore").css("display", "block");
            $(this).css("display", "none")
        })
    </script>
}